# Generated by Django 5.1.6 on 2025-02-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_currency_alter_item_description_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('items', models.ManyToManyField(to='items.item')),
            ],
        ),
    ]
