# Generated by Django 5.1.6 on 2025-02-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
